# 튜토리얼
## gpu 동작 체크

In [2]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

In [3]:
(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

# 픽셀 값을 0~1 사이로 정규화합니다.
train_images, test_images = train_images / 255.0, test_images / 255.0

11490434/11490434 [==============================] - 4s 0us/step


In [4]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))

In [5]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
Total params: 55,744
Trainable params: 55,744
Non-traina

In [6]:
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [7]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 26, 26, 32)        320       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 13, 13, 32)       0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 11, 11, 64)        18496     
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 5, 5, 64)         0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 3, 3, 64)          36928     
                                                                 
 flatten (Flatten)           (None, 576)               0

In [11]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])


model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0152 - accuracy: 0.9952
Epoch 2/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0122 - accuracy: 0.9958
Epoch 3/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0113 - accuracy: 0.9963
Epoch 4/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0090 - accuracy: 0.9971
Epoch 5/5
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0078 - accuracy: 0.9975


In [9]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

313/313 - 0s - loss: 0.0337 - accuracy: 0.9897 - 466ms/epoch - 1ms/step


In [10]:
print(test_acc)

0.9897000193595886


# tensor

In [12]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [13]:
# 텐서 생성

tensor = tf.constant([2, 3, 4])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 4])>

In [15]:
# 배열 변환
import numpy as np

np.array(tensor)

array([2, 3, 4])

In [16]:
# 랜덤 텐서 생성
rtensor = tf.random.uniform(shape=(10,5))
rtensor

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.43502498, 0.1251514 , 0.6267148 , 0.10038018, 0.05056894],
       [0.9316791 , 0.02473855, 0.6179588 , 0.30601776, 0.24428213],
       [0.36967957, 0.18102264, 0.26774192, 0.9197304 , 0.1385094 ],
       [0.8170675 , 0.8229486 , 0.9865459 , 0.40998328, 0.56939614],
       [0.97122574, 0.7162316 , 0.963446  , 0.14590347, 0.09903049],
       [0.49283552, 0.5931488 , 0.9818475 , 0.4107616 , 0.00400972],
       [0.59481704, 0.9991362 , 0.56084263, 0.41057003, 0.9470899 ],
       [0.8896364 , 0.4957626 , 0.95691836, 0.7559941 , 0.8756497 ],
       [0.4328612 , 0.15511549, 0.4319589 , 0.5991019 , 0.2025404 ],
       [0.31873703, 0.68574333, 0.8196186 , 0.02972102, 0.18222833]],
      dtype=float32)>

# Dens Layer

In [18]:
# 선형 레이어
dense = layers.Dense(16)

x = dense(rtensor)
# 결과값
print(x.shape)

# 가중치
wb = dense.get_weights()
print(wb)
print(wb[0].shape)

(10, 16)
[array([[ 0.3298766 ,  0.10799211,  0.16912317,  0.18900102,  0.17177981,
        -0.3058213 , -0.22250262, -0.52544045, -0.3829404 , -0.14740407,
         0.2980407 , -0.36852157, -0.06753013, -0.17327276,  0.01633167,
         0.01040268],
       [ 0.18374187,  0.35272866,  0.4000277 , -0.34876174,  0.534141  ,
         0.01438749, -0.34469256, -0.4172288 , -0.5018538 , -0.44319686,
        -0.03477597, -0.15939504, -0.5157253 ,  0.14140254,  0.11851662,
        -0.32980132],
       [-0.29320496,  0.3634863 ,  0.4659962 ,  0.16487473, -0.43329477,
         0.49750322,  0.04120111,  0.4167046 ,  0.23231447, -0.14344963,
         0.3118431 ,  0.30764562,  0.42671084,  0.23241186, -0.00931233,
        -0.37542766],
       [ 0.49887568, -0.11831385, -0.17298171,  0.25841725,  0.01987171,
         0.15908498,  0.22309703, -0.1910494 ,  0.38315678,  0.0165714 ,
         0.234613  , -0.28522608,  0.04332858, -0.0770207 , -0.04250878,
        -0.11308536],
       [ 0.48337942,  0.48

## 실습 문제
```
## (32, 10) 의 모양을 가지는 랜덤한 텐서를 생성
## 선형레이어 통과시 결과 모양이 (32, 5) 가 되게 Dense레이어 구성하여 결과값 모양 출력
```

In [20]:
# 랜덤 텐서 생성
rtensor = tf.random.uniform(shape=(32,10))
rtensor.shape

TensorShape([32, 10])

In [21]:
# 선형 레이어
dense = layers.Dense(5)

x = dense(rtensor)
# 결과값
print(x.shape)

(32, 5)


# DNN

In [22]:
# DNN

d_layer1 = layers.Dense(16)
d_layer2 = layers.Dense(32)
d_layer3 = layers.Dense(16)
d_layer4 = layers.Dense(1)

inp = tf.random.uniform(shape=(10,5))
x = d_layer1(inp)
print(x.shape)
x = d_layer2(x)
print(x.shape)
x = d_layer3(x)
print(x.shape)
out = d_layer4(x)

out

(10, 16)
(10, 32)
(10, 16)


<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.24337545],
       [-0.12422206],
       [-1.0402021 ],
       [-0.4100626 ],
       [-1.1311109 ],
       [-1.0277725 ],
       [-0.33844194],
       [-0.28106406],
       [-0.30696493],
       [-0.38333434]], dtype=float32)>

In [30]:
# 모델링

d_layer1 = layers.Dense(16)
d_layer2 = layers.Dense(32)
d_layer3 = layers.Dense(16)
d_layer4 = layers.Dense(1)

inp = keras.Input((5,)) # (batch size, data size)
x = d_layer1(inp)
x = d_layer2(x)
x = d_layer3(x)
out = d_layer4(x)

model = keras.Model(inp, out)
model.summary()

Model: "model_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 5)]               0         
                                                                 
 dense_21 (Dense)            (None, 16)                96        
                                                                 
 dense_22 (Dense)            (None, 32)                544       
                                                                 
 dense_23 (Dense)            (None, 16)                528       
                                                                 
 dense_24 (Dense)            (None, 1)                 17        
                                                                 
Total params: 1,185
Trainable params: 1,185
Non-trainable params: 0
_________________________________________________________________


# Activation Function

In [23]:
# 활성화 함수 레이어
# relu 활성화 : 음수를 0으로
dense = layers.Dense(5)
relu = layers.ReLU()

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x = relu(x)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.41544506, 0.        , 0.11183709, 0.        , 0.        ],
       [0.65014565, 0.        , 0.20044506, 0.        , 0.        ],
       [0.53855306, 0.        , 0.11883861, 0.2034648 , 0.        ],
       [0.56647927, 0.        , 0.14487904, 0.49177843, 0.        ],
       [0.9943846 , 0.12685692, 0.10044399, 0.09211752, 0.        ],
       [1.0037186 , 0.        , 0.58965486, 0.34901118, 0.        ],
       [0.4143224 , 0.        , 0.35938713, 0.38844022, 0.        ],
       [0.35652527, 0.        , 0.21733496, 0.00879884, 0.        ],
       [1.0898137 , 0.        , 0.44541457, 0.        , 0.        ],
       [0.5697756 , 0.        , 0.3466894 , 0.80007535, 0.07455312]],
      dtype=float32)>

In [24]:
dense = layers.Dense(5, activation = 'relu')

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.        , 0.20800412, 0.41380563, 0.240946  , 0.        ],
       [0.        , 0.6375983 , 0.32689098, 0.        , 0.        ],
       [0.        , 0.        , 0.19985804, 0.21180809, 0.        ],
       [0.        , 0.17744084, 0.2401489 , 0.        , 0.        ],
       [0.        , 0.7401287 , 0.5154611 , 0.        , 0.        ],
       [0.        , 0.55558395, 0.        , 0.        , 0.        ],
       [0.        , 1.0653319 , 0.27249917, 0.        , 0.        ],
       [0.        , 1.0944846 , 0.30326208, 0.        , 0.        ],
       [0.        , 0.5744695 , 0.        , 0.        , 0.        ],
       [0.        , 0.659779  , 0.71958935, 0.        , 0.        ]],
      dtype=float32)>

In [25]:
# 소프트 맥스 활성화
# 하나의 출력 텐서로 부터 확률값 산출 (전부더하면 1)
dense = layers.Dense(5)
smax = layers.Softmax()

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x = smax(x)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.1600563 , 0.1765538 , 0.4311515 , 0.07939272, 0.15284567],
       [0.16034   , 0.13833505, 0.50359374, 0.10525294, 0.09247828],
       [0.1136341 , 0.31351054, 0.335819  , 0.11744015, 0.11959623],
       [0.18168901, 0.22792582, 0.2678378 , 0.15512845, 0.16741891],
       [0.14296603, 0.2533483 , 0.33689135, 0.14552552, 0.12126892],
       [0.14001286, 0.25263503, 0.3784629 , 0.1100572 , 0.11883196],
       [0.11819687, 0.26623413, 0.37106457, 0.16872492, 0.07577954],
       [0.20943734, 0.19454229, 0.30323032, 0.13456881, 0.15822126],
       [0.21919549, 0.16310741, 0.25306433, 0.19966719, 0.16496563],
       [0.12003978, 0.22080427, 0.4428352 , 0.07249688, 0.14382388]],
      dtype=float32)>

## 실습 문제
```
# 다음 모델을 구성
# input 모양은 (2)
# 1번레이어: 5개의 유닛을 가지는 선형레이어
# 2번레이어: 10개의 유닛을 가지고 relu 활성화 함수를 가지는 선형레이어
# 3번레이어: 5개의 유닛을 가지는 선형레이어
# 4번레이어: sotfmax 활성화 함수 레이어
# keras Model 화 진행후 summary 출력
```

In [28]:
d_layer1 = layers.Dense(5)
d_layer2 = layers.Dense(10, activation = 'relu')
d_layer3 = layers.Dense(5)
d_layer4 = layers.Softmax()

inp = keras.Input((2,)) # (batch size, data size)
x = d_layer1(inp)
x = d_layer2(x)
x = d_layer3(x)
out = d_layer4(x)

model = keras.Model(inp, out)
model.summary()

Model: "model_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_3 (InputLayer)        [(None, 2)]               0         
                                                                 
 dense_18 (Dense)            (None, 5)                 15        
                                                                 
 dense_19 (Dense)            (None, 10)                60        
                                                                 
 dense_20 (Dense)            (None, 5)                 55        
                                                                 
 softmax_3 (Softmax)         (None, 5)                 0         
                                                                 
Total params: 130
Trainable params: 130
Non-trainable params: 0
_________________________________________________________________


# Convolution Layer

In [29]:
# 컨볼루션 레이어

inp = tf.random.uniform(shape=(1,16,16,3)) # 1개의 가상 이미지 데이터 생성 

# 커널개수, 커널사이즈, 스트라이드, 패딩
conv_layer = layers.Conv2D(8, 3, 1, padding = 'same') 
# padding same은 좌우 또는 상하에 균일하게 0으로 패딩
# padding same 또는 strides 1의 경우, 결국 출력은 입력과 동일한 크기
x = conv_layer(inp)
print(x.shape)

wb = conv_layer.get_weights()
print(wb[0].shape)

(1, 16, 16, 8)
(3, 3, 3, 8)


In [30]:
conv_layer2 = layers.Conv2D(16, 3, 2)
x = conv_layer2(inp)
print(x.shape)


(1, 7, 7, 16)


## 실습 문제

In [33]:
# 커널개수가 10, 커널사이즈가 5, 스트라이드가 2인 컨볼루션 레이어를 통과시킨 inp의 결과값 모양 출력
inp = tf.random.uniform(shape=(1,8,8,2))
conv_layer = layers.Conv2D(10, 5, 2) 
x = conv_layer(inp)
print(x.shape)

wb = conv_layer.get_weights()
print(wb[0].shape)

(1, 2, 2, 10)
(5, 5, 2, 10)


# CNN

In [34]:
# CNN 
# 커널개수를 작은 수에서 점차 늘리는 이유는, 처음부터 데이터 수를 확 늘려버리면 오히려 (특징)데이터 손실을 야기할 수 있기 때문
conv_layer1 = layers.Conv2D(8, 3, 1, padding = 'same')
conv_layer2 = layers.Conv2D(16, 3, 2)
conv_layer3 = layers.Conv2D(32, 3, 1)

flatten = layers.Flatten() #  FC Layer

d_layer1 = layers.Dense(32) 
d_layer2 = layers.Dense(1)

inp = tf.random.uniform(shape=(1,16,16,3))
x = conv_layer1(inp)
print(x.shape)
x = conv_layer2(x)
print(x.shape)
x = conv_layer3(x)
print(x.shape)
x = flatten(x)
print(x.shape)
x = d_layer1(x)
print(x.shape)
out = d_layer2(x)
out

(1, 16, 16, 8)
(1, 7, 7, 16)
(1, 5, 5, 32)
(1, 800)
(1, 32)


<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[1.2773787]], dtype=float32)>

In [39]:
# 모델링

conv_layer1 = layers.Conv2D(8, 3, 1, padding = 'same')
conv_layer2 = layers.Conv2D(16, 3, 2)
conv_layer3 = layers.Conv2D(32, 3, 1)

flatten = layers.Flatten()

d_layer1 = layers.Dense(32)
d_layer2 = layers.Dense(1)

inp = keras.Input((16,16,3))
x = conv_layer1(inp)
x = conv_layer2(x)
x = conv_layer3(x)
x = flatten(x)
x = d_layer1(x)
out = d_layer2(x)

model = keras.Model(inp, out)
model.summary()

Model: "model_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_6 (InputLayer)        [(None, 16, 16, 3)]       0         
                                                                 
 conv2d_13 (Conv2D)          (None, 16, 16, 8)         224       
                                                                 
 conv2d_14 (Conv2D)          (None, 7, 7, 16)          1168      
                                                                 
 conv2d_15 (Conv2D)          (None, 5, 5, 32)          4640      
                                                                 
 flatten_3 (Flatten)         (None, 800)               0         
                                                                 
 dense_25 (Dense)            (None, 32)                25632     
                                                                 
 dense_26 (Dense)            (None, 1)                 33  

In [33]:
# 활성화 함수 레이어
# relu 활성화 : 음수를 0으로
dense = layers.Dense(5)
relu = layers.ReLU()

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x = relu(x)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.4942127 , 0.26164243, 0.046472  , 0.7654542 , 0.        ],
       [0.770815  , 0.34618673, 0.        , 0.13107927, 0.        ],
       [0.45719987, 0.        , 0.        , 0.5406862 , 0.        ],
       [1.1433494 , 0.        , 0.        , 0.34604597, 0.        ],
       [0.62140197, 0.4175714 , 0.        , 0.        , 0.        ],
       [0.85103077, 0.2547932 , 0.        , 0.25941783, 0.        ],
       [0.7361645 , 0.        , 0.        , 0.        , 0.        ],
       [1.2917184 , 0.25360128, 0.        , 0.84500253, 0.        ],
       [1.0582116 , 0.30154526, 0.        , 0.        , 0.        ],
       [0.9180781 , 0.        , 0.        , 0.4594703 , 0.        ]],
      dtype=float32)>

In [34]:
dense = layers.Dense(5, activation = 'relu')

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.        , 0.        , 0.32145786, 0.        , 0.1247461 ],
       [0.        , 0.        , 0.5386183 , 0.        , 0.00729177],
       [0.        , 0.        , 0.5743971 , 0.        , 0.32320166],
       [0.        , 0.        , 0.04828465, 0.        , 0.21370819],
       [0.        , 0.        , 0.00435197, 0.        , 0.3775684 ],
       [0.        , 0.        , 0.16364774, 0.        , 0.55140436],
       [0.        , 0.        , 0.67150384, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.00176896, 0.        , 0.        ],
       [0.        , 0.        , 0.71260166, 0.        , 0.3479255 ]],
      dtype=float32)>

In [35]:
# 소프트 맥스 활성화
# 하나의 출력 텐서로 부터 확률값 산출 (전부더하면 1)
dense = layers.Dense(5)
smax = layers.Softmax()

inp = tf.random.uniform(shape=(10,10))
x = dense(inp)
x = smax(x)
x

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.1484716 , 0.30648792, 0.19968241, 0.27898318, 0.06637487],
       [0.09295511, 0.46970114, 0.08034788, 0.3177434 , 0.03925246],
       [0.21100253, 0.27778092, 0.14134459, 0.25171635, 0.11815562],
       [0.09882341, 0.42677504, 0.09338861, 0.32649806, 0.0545149 ],
       [0.12183032, 0.4999922 , 0.11927192, 0.2194304 , 0.03947509],
       [0.12288448, 0.22859643, 0.09234601, 0.44808733, 0.10808574],
       [0.13685594, 0.51479965, 0.10803685, 0.18187158, 0.05843596],
       [0.13076557, 0.40906745, 0.08633816, 0.27748284, 0.09634596],
       [0.11412358, 0.33287847, 0.10277636, 0.34275147, 0.10747001],
       [0.08694641, 0.28096098, 0.10420871, 0.475875  , 0.05200892]],
      dtype=float32)>

# Normalization Layer

In [35]:
# 정규화 레이어
# 이상치와 같은 값을 정리해주면 학습 퍼포먼스가 더 좋아짐
bn = layers.BatchNormalization()
inp = tf.random.uniform(shape=(10,10))
x = bn(inp)
x

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[6.7817831e-01, 5.4054999e-01, 1.3320940e-04, 9.8234659e-01,
        6.7201948e-01, 6.6717470e-01, 3.3896118e-01, 4.9804074e-01,
        9.5145953e-01, 1.7278616e-01],
       [6.5309250e-01, 2.0577669e-01, 3.3807459e-01, 9.9889767e-01,
        7.0851660e-01, 4.8687187e-01, 9.9747455e-01, 4.1385931e-01,
        4.4292015e-01, 2.9327750e-01],
       [1.5595269e-02, 1.9039173e-01, 5.2097547e-01, 6.4895874e-01,
        2.7698058e-01, 7.2290462e-01, 9.6807021e-01, 4.8705667e-01,
        9.0187170e-02, 2.0927279e-01],
       [2.5505036e-01, 8.8248193e-01, 5.9810030e-01, 2.2831553e-01,
        7.8051887e-02, 7.7441698e-01, 2.8558484e-01, 9.6999790e-04,
        6.6151071e-01, 6.4652666e-02],
       [2.9120418e-01, 5.6296003e-01, 3.7384382e-01, 5.5622703e-01,
        4.5356333e-01, 5.6340724e-01, 8.2197607e-01, 7.3001844e-01,
        3.5837865e-01, 2.9246694e-01],
       [8.2593340e-01, 8.2550550e-01, 5.8024067e-01, 6.6330887e-02,
       

In [36]:
# 드롭아웃 레이어: 학습시 확률 초기화

drop = layers.Dropout(0.5) # 50%확률로 0으로 설정: 과적합 방지
inp = tf.random.uniform(shape=(5,3))
x = drop(inp)

## 실습 문제
```
# 다음 모델을 구성
# input 모양은 (28,28,1)
# 1번레이어: 커널사이즈 5, 커널개수 10, 스트라이드 1 을가지는 컨볼루션 레이어
# 2번레이어: 커널사이즈 3, 커널개수 20, 스트라이드 2, relu 활성화 함수 를가지는 컨볼루션 레이어
# 3번레이어: 커널사이즈 1, 커널개수 20, 스트라이드 2, 패딩 'same' 을가지는 컨볼루션 레이어
# 4번레이어: flatten 레이어
# 5번레이어: 배치 정규화 레이어
# 6번레이어: 20퍼센트 확률로 초기화하는 dropout 레이어
# 7번레이어: 유닛개수가 64개인 레이어
# 8번레이어: 유닛개수가 10개인 레이어
# 9번레이어: 소프트맥스 활성화 함수 레이어
# keras Model 화 진행후 summary 출력
```

In [45]:
conv_layer1 = layers.Conv2D(10, 5, 1)
conv_layer2 = layers.Conv2D(20, 3, 2, activation = 'relu')
conv_layer3 = layers.Conv2D(20, 1, 2, padding='same') # 커널사이즈가 1이므로 사실 패딩 불필요
flat_layer4 = layers.Flatten() 
bn_layer5 = layers.BatchNormalization()
drop_layer6 = layers.Dropout(0.2)
d_layer7 = layers.Dense(64)
d_layer8 = layers.Dense(10)
smax_layer9 = layers.Softmax()


inp = keras.Input((28,28,1)) 
x = conv_layer1(inp)
x = conv_layer2(x)
x = conv_layer3(x)
x = flat_layer4(x)
x = bn_layer5(x)
x = drop_layer6(x)
x = d_layer7(x)
x = d_layer8(x)
out = smax_layer9(x)

model = keras.Model(inp, out)
model.summary()

Model: "model_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_12 (InputLayer)       [(None, 28, 28, 1)]       0         
                                                                 
 conv2d_31 (Conv2D)          (None, 24, 24, 10)        260       
                                                                 
 conv2d_32 (Conv2D)          (None, 11, 11, 20)        1820      
                                                                 
 conv2d_33 (Conv2D)          (None, 6, 6, 20)          420       
                                                                 
 flatten_9 (Flatten)         (None, 720)               0         
                                                                 
 batch_normalization_7 (Batc  (None, 720)              2880      
 hNormalization)                                                 
                                                          

# Loss Function, Optimizer, Model Train

In [46]:
# 손실함수, 최적화 알고리즘적용
# compile 함수 사용

model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False), 
    # sparseCC, 다항 분류에서 출력으로 softmax를 사용할 때, 라벨이 범주 인덱스 일 때(원핫인코딩 불가)
    #  logits 입력값이 확률값인데 선형값인지 입력
    optimizer=keras.optimizers.Adam(learning_rate = 0.001),
    metrics=["accuracy"],
)

In [50]:
# 학습 하기
# fit(x,y,batch_size, epochs, validation_split...)함수 사용 
# x: 입력데이터세트, y: 라벨데이터세트
# validation_split: 과적합 방지를 위한 테스트 세트

from tensorflow.keras import datasets
(train_images, train_labels), (test_images, test_labels) = datasets.mnist.load_data()

train_images = train_images.reshape((60000, 28, 28, 1))
test_images = test_images.reshape((10000, 28, 28, 1))

# 픽셀 값을 0~1 사이로 정규화합니다.
train_images, test_images = train_images / 255.0, test_images / 255.0

model.fit(train_images, train_labels, batch_size=16, epochs=2, validation_split=0.2)


Epoch 1/2
3000/3000 [==============================] - 6s 2ms/step - loss: 0.1511 - accuracy: 0.9541 - val_loss: 0.1038 - val_accuracy: 0.9690
Epoch 2/2
3000/3000 [==============================] - 6s 2ms/step - loss: 0.1378 - accuracy: 0.9570 - val_loss: 0.0956 - val_accuracy: 0.9733


In [49]:
test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)

313/313 - 0s - loss: 0.0839 - accuracy: 0.9714 - 396ms/epoch - 1ms/step
