# NumPy(Numerical Python)

* 수학 및 과학적 연산을 쉽고 빠르게 지원
* 다차원 <font color = 'blue'>행렬</font>(Array/Matrix)을 효과적으로 처리
* 일반적으로 <font color = 'red'>같은 데이터 타입 값</font>으로 구성
* https://numpy.org

In [8]:
import warnings
warnings.filterwarnings('ignore')

# I. NumPy Package import ~ as

In [9]:
import numpy as np 

* Version Check

In [10]:
np.__version__

'1.23.5'

# II. Array 생성

* Python <font color = 'blue'>List 구조</font>를 사용

>## 1) Scalar - 0D Array - Rank0 Tensor
> 방향성 없이 양만 존재

In [11]:
# interger to array casing
a0 = np.array(9)

In [12]:
print(a0, type(a0))

9 <class 'numpy.ndarray'>


>## 2) Vector - 1D Array - Rank1 Tensor

In [13]:
a1 = np.array([1, 3, 5, 7, 9])

In [14]:
print(a1)

[1 3 5 7 9]


In [15]:
a1[2]

5

In [16]:
a1[1:3]

array([3, 5])

>## 3) Matrix - 2D Array - Rank2 Tensor

In [17]:
a2 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

In [18]:
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* a2[행]

In [19]:
a2[1]

array([4, 5, 6])

* a2[행, 열]

In [20]:
a2[1, 1]

5

* a2[<font color = 'blue'>행</font>, 열]

In [21]:
a2[:, 1]

array([2, 5, 8])

>## 4) Array - 3D Array - Rank3 Tensor

In [22]:
a3 = np.array([[[1, 2],
                [3, 4]],
               [[5, 6],
                [7, 8]],
               [[9, 10],
                [11, 12]]])

In [23]:
print(a3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* a3[축]

In [25]:
a3[1]

array([[5, 6],
       [7, 8]])

* a3[축, 행]

In [28]:
a3[1, 1]

array([7, 8])

* a3[축, 행, 열]

In [29]:
a3[1, 1, 1]

8

* a3[<font color = 'blue'>축</font>, 행, 열]

In [30]:
a3[:, 0, 0]

array([1, 5, 9])

* a3[<font color = 'blue'>축</font>, <font color = 'blue'>행</font>, 열]

In [31]:
a3[:, :, 0]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

# III. AR.shape and AR.reshape( )

In [32]:
AR = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [33]:
print(AR)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


>## 1) .shape

* 행렬 크기

In [37]:
AR.shape , a3.shape

((12,), (3, 2, 2))

* 행렬 차원

In [41]:
AR.ndim, a3.reshape

(1, <function ndarray.reshape>)

* 행렬 원소 개수

In [39]:
AR.size, a3.size

(12, 12)

>## 2) .reshape(3, 4)

* <font color = 'blue'>.reshape(</font>행, 열<font color = 'blue'>)</font>

In [42]:
AR2 = AR.reshape(3, 4)

In [43]:
print(AR2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


* 행렬 크기

In [44]:
AR2.shape 

(3, 4)

* 행렬 차원

In [45]:
AR2.ndim

2

* 행렬 원소 개수

In [46]:
AR2.size

12

>## 3) .reshape(3, 2, 2)

* .reshape(<font color = 'red'>축</font>, 행, 열)

In [47]:
AR3 = AR.reshape(3, 2, 2)

In [48]:
print(AR3)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


* 행렬의 크기

In [49]:
AR3.shape

(3, 2, 2)

* 행렬의 차원

In [50]:
AR3.ndim

3

* 행렬의 원소 개수

In [51]:
AR3.size

12

>## 4) .reshape(<font color = 'red'>-1</font>, 1)

* .reshape(<font color = 'red'>12</font>, 1)

In [52]:
AR.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

   * .reshape(1, <font color = 'blue'>12</font>)

In [54]:
AR2.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [55]:
AR2.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [56]:
AR3.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

* <font color = 'blue'>.flatten( )

In [ ]:
AR3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# IV. 범위 지정(arange) 함수

>## 1) 연속된 10개 값 생성

In [57]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 2) 1부터 9까지 <font color = 'blue'>1간격</font>으로 생성

In [58]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

>## 3) 1부터 9까지 <font color = 'red'>2간격</font>으로 생성

In [59]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

>## 4) Array 생성 후 <font color = 'blue'>.reshape( )</font> 적용

In [60]:
np.arange(1, 10).reshape(3, 3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# V. 특별한 형태의 Array 생성

>## 1) 0과 1로만 구성된 Array

* <font color = 'blue'>0으로만 구성

In [61]:
np.zeros(9)

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [63]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

* <font color = 'blue'>1로만 구성

In [64]:
np.ones(9)

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [65]:
np.ones([4, 3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

* 산술연산을 적용하여 <font color = 'blue'>'9'로만 구성</font>된 행렬 생성

In [66]:
np.zeros([3, 4]) + 9

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.],
       [9., 9., 9., 9.]])

>## 2) 3 x 3 <font color = 'red'>단위행렬

In [67]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

>## 3) 난수 Array 생성

* <font color = 'blue'>실수</font> 난수 생성
 - (축, 행, 열)

In [69]:
np.random.rand(3, 2, 2)

array([[[0.32122129, 0.7989216 ],
        [0.60015844, 0.84771823]],

       [[0.0845911 , 0.96093831],
        [0.47522374, 0.14259901]],

       [[0.02731709, 0.19692261],
        [0.44043054, 0.60780881]]])

* 주어진 <font color = 'blue'>정수</font> 범위에서 난수 생성
 - 1 ~ 44 사이
 - 복원 추출
 - (행, 열)

In [70]:
np.random.randint(1, 45, size = (5, 6))

array([[33, 18, 42,  2, 38,  1],
       [32, 23, 38, 42, 32, 10],
       [38, 31, 14, 41, 28,  7],
       [11, 42,  4, 15, 33, 21],
       [17, 26, 11,  7, 34, 38]])

* np.random.<font color = 'red'>seed( )</font>
 - 의사난수(Pseudo(가짜) Random Number) 생성 초기값 지정
 - <font color = 'red'>항상 같은 난수 생성</font>
 - 비복원 추출

In [72]:
# np.random.seed(2045)
np.random.choice(np.arange(1, 46), size = (5 ,6), replace = False) # replace false 비복원추출

array([[16, 14, 38, 27, 42, 13],
       [ 7,  4, 39, 20, 15, 40],
       [28, 45, 17,  9, 19,  8],
       [10, 30, 22, 36, 44, 21],
       [29, 25,  3,  1,  6, 34]])

* <font color = 'blue'>shuffle( )</font>
 - 원소 섞기

In [73]:
TA = np.arange(1, 10)

TA

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np.random.shuffle(TA)

TA

array([9, 3, 6, 5, 1, 2, 8, 7, 4])

# VI. Array 연산

In [77]:
l1 = [85, 93, 75, 97, 69]

l2 = [91, 90, 85, 97, 89]

In [78]:
# 연산이 아닌 concat이 되버림
l1+l2

[85, 93, 75, 97, 69, 91, 90, 85, 97, 89]

In [79]:
A1 = np.array([85, 93, 75, 97, 69])

A2 = np.array([91, 90, 85, 97, 89])

A3 = np.array([[85, 93, 75],
               [90, 84, 97],
               [99, 91, 80]])

>## 1) 기본 연산

* 각각의 <font color = 'blue'>행과 열의 값을 매칭</font>하여 연산 수행
* 벡터화 연산(vectorized operation)

In [80]:
A1 + A2

array([176, 183, 160, 194, 158])

In [81]:
A2 - A1

array([ 6, -3, 10,  0, 20])

In [82]:
A1 * A2

array([7735, 8370, 6375, 9409, 6141])

In [83]:
A2 / A1

array([1.07058824, 0.96774194, 1.13333333, 1.        , 1.28985507])

In [84]:
A1 * 3

array([255, 279, 225, 291, 207])

In [85]:
A1 ** 2

array([7225, 8649, 5625, 9409, 4761])

>## 2) 통계량 연산

* 총합

In [86]:
A1.sum()

419

* 평균

In [87]:
A2.mean()

90.4

* 분산
 - 'ddof = 0'
 - degree of freedom, 자유도

In [88]:
A2.var()

15.040000000000001

* 표준 편차
 - 'ddof = 0'

In [89]:
A2.std()

3.8781438859330635

* 최소값

In [93]:
A2

array([91, 90, 85, 97, 89])

In [90]:
A2.min()

85

> * A3 전체 최소값

  

In [94]:
A3

array([[85, 93, 75],
       [90, 84, 97],
       [99, 91, 80]])

In [91]:
A3.min()

75

> * A3 각 열의 최소값(행의 방향)

In [95]:
A3.min(axis = 0)

array([85, 84, 75])

> * A3 각 행의 최소값(열의 방향)

In [96]:
A3.min(axis = 1)

array([75, 84, 80])

In [98]:
A3.min(axis = 1, keepdims = True)

array([[75],
       [84],
       [80]])

* 최대값

In [99]:
A2.max()

97

> * A3 전체 최대값

In [100]:
A3.max()

99

> * A3 각 열의 최대값

In [ ]:
A3.max(axis = 0)

array([99, 93, 97])

> * A3 각 행의 최대값

In [101]:
A3.max(axis = 1)

array([93, 97, 99])

In [102]:
A3.max(axis = 1, keepdims = True)

array([[93],
       [97],
       [99]])

* 누적(Cumulative)합

In [103]:
A1

array([85, 93, 75, 97, 69])

In [104]:
A1.cumsum()

array([ 85, 178, 253, 350, 419])

* 누적(Cumulative)곱

In [105]:
A1.cumprod()

array([        85,       7905,     592875,   57508875, -326854921])

# VII. Matrix 연산

* M1, M2 지정

In [106]:
M1 = np.array([2, 4, 6, 8]).reshape(2, 2)

In [107]:
print(M1)

[[2 4]
 [6 8]]


In [108]:
M2 = np.array([3, 5, 7, 9]).reshape(2, 2)

In [109]:
print(M2)

[[3 5]
 [7 9]]


>## 1) Matrix 곱

* M1 @ M2

In [ ]:
M1.dot(M2)

array([[ 34,  46],
       [ 74, 102]])

* M2 @ M1

In [110]:
np.dot(M2, M1)

array([[ 36,  52],
       [ 68, 100]])

* Warning : M1 * M2 
* vertorizing operation

In [111]:
M1 * M2

array([[ 6, 20],
       [42, 72]])

In [ ]:
M2 * M1

array([[ 6, 20],
       [42, 72]])

>## 2) 전치 행렬

* M1의 전치 행렬

In [114]:
M1

array([[2, 4],
       [6, 8]])

In [112]:
np.transpose(M1)

array([[2, 6],
       [4, 8]])

* M2의 전치 행렬

In [115]:
M2.transpose()

array([[3, 7],
       [5, 9]])

In [116]:
M2.T

array([[3, 7],
       [5, 9]])

# 
# 
# 
# The End
# 
# 
# 